In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A", "B", "C"], index=["x","y","z",'zz'])

#shows first couple rows
df.head()

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [3]:
#shows last couple rows
df.tail(2)

     A   B   C
z    7   8   9
zz  10  11  12

In [4]:
#describes columns as a  list
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [5]:
#shows index as a list
df.index.tolist()

['x', 'y', 'z', 'zz']

In [7]:
#gives info on the dataframe
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, x to zz
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 133.0 bytes

In [8]:
#provides basic statistics on the dataframe

df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [9]:
#provides unique number of values in each column
df.nunique()

A    4
B    4
C    4
dtype: int64

In [12]:
#returns a list of unique value in each column
df['A'].unique()

array([ 1,  4,  7, 10])

In [13]:
# df.shape describes the dimensions of the dataframe
df.shape

(4, 3)

In [14]:
#df.size describes the number of unit cells
df.size

12

In [15]:
df

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [48]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
results = pd.read_parquet('./data/results.parquet')
bios = pd.read_csv('./data/bios.csv')
## To read an excel spreadsheet
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name="results")

In [21]:
#accessing data with pandas

print(type(coffee))
print(coffee)

<class 'pandas.DataFrame'>
          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [19]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [22]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [24]:
coffee.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [25]:
coffee.sample(5)

         Day Coffee Type  Units Sold
7   Thursday       Latte          30
8     Friday    Espresso          45
1     Monday       Latte          15
2    Tuesday    Espresso          30
10  Saturday    Espresso          45

In [26]:
#loc
# coffee.loc[row,columns]

coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [29]:
coffee.loc[[0,1,5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [30]:
coffee.loc[[0]]

      Day Coffee Type  Units Sold
0  Monday    Espresso          25

In [33]:
#how to select rows from slice and select specific columns
coffee.loc[5:9,["Day","Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45
9     Friday          35

In [32]:
coffee.loc[[5,6,7],["Day","Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30

In [34]:
#iloc focuses on using index positions
coffee.iloc[:,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [40]:
coffee.iloc[:,:]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [42]:
#change the index to the day column
coffee.index = coffee["Day"]
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [44]:
# can select the index
coffee.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [50]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [52]:
#setting values
coffee.loc[1:3,"Units Sold"] = 10
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [53]:
coffee.at[0,"Units Sold"]

np.int64(25)

In [55]:
coffee.iat[3,1]

'Latte'

In [56]:
# Getting Columns
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [58]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [62]:
#can sort values by using just string or using a list for multiple
coffee.sort_values(["Units Sold","Day"],ascending=True)

          Day Coffee Type  Units Sold
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [63]:
coffee.sort_values(["Units Sold", "Coffee Type"],ascending = [0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [65]:
#Iterating over dataframe with for loop
for index,row in coffee.iterrows():
    print(index)
    print(row)
    print("coffee Type of Row:",row["Coffee Type"])

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
coffee Type of Row: Espresso
1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
coffee Type of Row: Latte
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           10
Name: 2, dtype: object
coffee Type of Row: Espresso
3
Day            Tuesday
Coffee Type      Latte
Units Sold          10
Name: 3, dtype: object
coffee Type of Row: Latte
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
coffee Type of Row: Espresso
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
coffee Type of Row: Latte
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
coffee Type of Row: Espresso
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
coffee Type of Row: Latte
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
coffee Type of Row: Espresso
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
coffee Type of Row: Latte
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
coffee Type of Row: Espresso
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
coffee Type of Row: Latte
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
coffee Type of Row: Espresso
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
coffee Type of Row: Latte

In [66]:
#filtering the data
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [67]:
bios.loc[bios["height_cm"]>215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [68]:
bios.loc[bios["height_cm"]>215,["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [77]:
#short hand syntx (without.loc)

bios[bios["height_cm"]>215][["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [78]:
#multiple filter conditions
bios[(bios["height_cm"] > 215) & (bios["born_country" ] =="USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [79]:
#filter by string conditions
bios[bios["name"].str.contains("keith",case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [80]:
#regex syntax
bios[bios['name'].str.contains('keight|patrick',case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
2454,2465,Patrick Birocheau,1955-09-23,Béjaïa,Béjaïa,ALG,France,177.0,72.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [81]:
# Other cool regex filters

# Find athletes born in cities that start with a vowel:
vowel_cities = bios[bios['born_city'].str.contains(r'^[AEIOUaeiou]', na=False)]

# Find athletes with names that contain exactly two vowels:
two_vowels = bios[bios['name'].str.contains(r'^[^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*$', na=False)]

# Find athletes with names that have repeated consecutive letters (e.g., "Aaron", "Emmett"):
repeated_letters = bios[bios['name'].str.contains(r'(.)\1', na=False)]

# Find athletes with names ending in 'son' or 'sen':
son_sen_names = bios[bios['name'].str.contains(r'son$|sen$', case=False, na=False)]

# Find athletes born in a year starting with '19':
born_19xx = bios[bios['born_date'].str.contains(r'^19', na=False)]

# Find athletes with names that do not contain any vowels:
no_vowels = bios[bios['name'].str.contains(r'^[^AEIOUaeiou]*$', na=False)]

# Find athletes whose names contain a hyphen or an apostrophe:
hyphen_apostrophe = bios[bios['name'].str.contains(r"[-']", na=False)]

# Find athletes with names that start and end with the same letter:
start_end_same = bios[bios['name'].str.contains(r'^(.).*\1$', na=False, case=False)]

# Find athletes with a born_city that has exactly 7 characters:
city_seven_chars = bios[bios['born_city'].str.contains(r'^.{7}$', na=False)]

# Find athletes with names containing three or more vowels:
three_or_more_vowels = bios[bios['name'].str.contains(r'([AEIOUaeiou].*){3,}', na=False)]

C:\Users\Kempe\AppData\Local\Temp\ipykernel_36064\526288713.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  repeated_letters = bios[bios['name'].str.contains(r'(.)\1', na=False)]
C:\Users\Kempe\AppData\Local\Temp\ipykernel_36064\526288713.py:25: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  start_end_same = bios[bios['name'].str.contains(r'^(.).*\1$', na=False, case=False)]
C:\Users\Kempe\AppData\Local\Temp\ipykernel_36064\526288713.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  three_or_more_vowels = bios[bios['name'].str.contains(r'([AEIOUaeiou].*){3,}', na=False)]

In [83]:
#exact match search
bios[bios['name'].str.contains('keith|patric',case=False,regex=False)]

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [84]:
## isin method & startswith
bios[bios['born_country'].isin(["USA","FRA","GBR"]) & (bios['name'].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [85]:
#query functions

bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [86]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [88]:
coffee['price'] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          10   4.99
3    Tuesday       Latte          10   4.99
4  Wednesday    Espresso          35   4.99

In [90]:
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso',3.99,5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          10   4.99       5.99
2     Tuesday    Espresso          10   4.99       3.99
3     Tuesday       Latte          10   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [96]:
coffee.drop(columns='price',inplace=True)
coffee

KeyError: "['price'] not found in axis"

In [100]:
coffee
coffee = coffee[['Day','Coffee Type','Units Sold', 'new_price']]
coffee
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          10       5.99    59.90
2     Tuesday    Espresso          10       3.99    39.90
3     Tuesday       Latte          10       5.99    59.90
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [105]:
coffee.rename(columns = {'new_price':'price'},inplace=True)
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          10   5.99    59.90
2     Tuesday    Espresso          10   3.99    39.90
3     Tuesday       Latte          10   5.99    59.90
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [104]:
bios_new = bios.copy()

In [108]:
bios_new['first-name'] = bios_new['name'].str.split(' ').str[0]
bios_new = bios_new.rename(columns = {'first-name':'first_name'})
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [110]:
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [112]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith,1966-09-01
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,1961-03-29
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith,1940-10-15
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith,1966-01-01
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,1898-11-03
...,...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,1970-02-03
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith,1983-02-09
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith,1927-08-25
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,1975-02-02
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith,1979-09-07

In [114]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith,1966-09-01,1966.0
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,1961-03-29,1961.0
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith,1940-10-15,1940.0
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith,1966-01-01,1966.0
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,1898-11-03,1898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,1970-02-03,1970.0
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith,1983-02-09,1983.0
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith,1927-08-25,1927.0
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,1975-02-02,1975.0
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith,1979-09-07,1979.0

In [115]:
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [116]:
bios_new.to_csv('./data/bios_new.csv',index=False)

In [117]:
bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [119]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'
bios['Category'] = bios.apply(categorize_athlete, axis=1)
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [122]:
#merging and concatenating data

nocs = pd.read_csv('./data/noc_regions.csv')
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [123]:
bios_new = pd.merge(bios,nocs,left_on='born_country',right_on = 'NOC',how='left')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight,GBR,UK,NaN

In [124]:
bios_new.rename(columns = {'region':'born_country_full'},inplace=True)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight,GBR,UK,NaN

In [126]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Average,Middleweight
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Average,Lightweight
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Short,Lightweight
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Tall,Heavyweight
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Average,Lightweight

In [127]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,Tall,Heavyweight
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,Tall,Heavyweight
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,Tall,Heavyweight
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,Average,Middleweight

In [132]:
new_df = pd.concat([usa,gbr])
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Average,Middleweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall,Heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall,Heavyweight

In [133]:
combined_df = pd.merge(results,bios, on='athlete_id',how='left')
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight

In [141]:
# Handling null values
coffee.loc[[2,3],'Units Sold'] = np.nan
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso        25.0   3.99    99.75
1     Monday       Latte        10.0   5.99    59.90
2    Tuesday    Espresso         NaN   3.99    39.90
3    Tuesday       Latte         NaN   5.99    59.90
4  Wednesday    Espresso        35.0   3.99   139.65

In [148]:
# make sure to sets this to your units sold column if you want these changes to stick
coffee['Units Sold'] = coffee['Units Sold'].fillna(coffee['Units Sold'].mean())
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso       25.00   3.99    99.75
1     Monday       Latte       10.00   5.99    59.90
2    Tuesday    Espresso       33.75   3.99    39.90
3    Tuesday       Latte       33.75   5.99    59.90
4  Wednesday    Espresso       35.00   3.99   139.65

In [151]:
#interpolates what the data should be for the Na values based on nearby values
coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso       25.00   3.99    99.75
1      Monday       Latte       10.00   5.99    59.90
2     Tuesday    Espresso       33.75   3.99    39.90
3     Tuesday       Latte       33.75   5.99    59.90
4   Wednesday    Espresso       35.00   3.99   139.65
5   Wednesday       Latte       25.00   5.99   149.75
6    Thursday    Espresso       40.00   3.99   159.60
7    Thursday       Latte       30.00   5.99   179.70
8      Friday    Espresso       45.00   3.99   179.55
9      Friday       Latte       35.00   5.99   209.65
10   Saturday    Espresso       45.00   3.99   179.55
11   Saturday       Latte       35.00   5.99   209.65
12     Sunday    Espresso       45.00   3.99   179.55
13     Sunday       Latte       35.00   5.99   209.65

In [152]:
coffee.dropna(subset=['Units Sold']) # use inplace=true if you want to update coffee df

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso       25.00   3.99    99.75
1      Monday       Latte       10.00   5.99    59.90
2     Tuesday    Espresso       33.75   3.99    39.90
3     Tuesday       Latte       33.75   5.99    59.90
4   Wednesday    Espresso       35.00   3.99   139.65
5   Wednesday       Latte       25.00   5.99   149.75
6    Thursday    Espresso       40.00   3.99   159.60
7    Thursday       Latte       30.00   5.99   179.70
8      Friday    Espresso       45.00   3.99   179.55
9      Friday       Latte       35.00   5.99   209.65
10   Saturday    Espresso       45.00   3.99   179.55
11   Saturday       Latte       35.00   5.99   209.65
12     Sunday    Espresso       45.00   3.99   179.55
13     Sunday       Latte       35.00   5.99   209.65

In [155]:
coffee.loc[[2,3],"Units Sold"]=np.nan
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        25.0   3.99    99.75
1      Monday       Latte        10.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [156]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        25.0   3.99    99.75
1      Monday       Latte        10.0   5.99    59.90
2     Tuesday    Espresso         NaN   3.99    39.90
3     Tuesday       Latte         NaN   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [157]:
#aggregating Data
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [158]:
bios['born_city'].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [160]:
bios[bios['born_country']=='USA']['born_region'].value_counts().head(10)

born_region
California       1634
New York          990
Illinois          585
Pennsylvania      530
Massachusetts     530
New Jersey        381
Texas             368
Minnesota         365
Ohio              328
Michigan          319
Name: count, dtype: int64

In [162]:
bios['born_country']=='USA'

0         False
1         False
2         False
3         False
4         False
          ...
145495    False
145496    False
145497    False
145498    False
145499    False
Name: born_country, Length: 145500, dtype: bool

In [163]:
bios[bios['born_country']=='USA']['born_region'].value_counts().tail(25)

born_region
Utah              91
Missouri          91
North Carolina    86
Arizona           83
New Hampshire     83
Vermont           68
Mississippi       66
Alabama           64
Tennessee         62
Kentucky          62
Nebraska          60
Rhode Island      56
Montana           55
Maine             50
South Carolina    50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

In [165]:
#Groupby function in Pandas
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    235.0
Latte       170.0
Name: Units Sold, dtype: float64

In [166]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    39.166667
Latte       28.333333
Name: Units Sold, dtype: float64

In [168]:
coffee.groupby(['Coffee Type','Day']).agg({'Units Sold':'sum','price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday           45.0   3.99
            Monday           25.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Tuesday           0.0   3.99
            Wednesday        35.0   3.99
Latte       Friday           35.0   5.99
            Monday           10.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday         30.0   5.99
            Tuesday           0.0   5.99
            Wednesday        25.0   5.99

In [170]:
#Pivot Tables
pivot = coffee.pivot(columns='Coffee Type',index='Day',values='revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   59.90
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday         39.90   59.90
Wednesday      139.65  149.75

In [171]:
pivot.sum()

Coffee Type
Espresso     977.55
Latte       1078.20
dtype: float64

In [172]:
pivot.sum(axis=1)

Day
Friday       389.20
Monday       159.65
Saturday     389.20
Sunday       389.20
Thursday     339.30
Tuesday       99.80
Wednesday    289.40
dtype: float64

In [175]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,Lightweight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,Lightweight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Lightweight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,Middleweight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight

In [177]:
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight,4.0,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,Lightweight,1.0,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,Lightweight,9.0,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Lightweight,5.0,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,Middleweight,5.0,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,7.0,1913.0

In [178]:
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name',ascending=False)
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight,4.0,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,Lightweight,1.0,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,Lightweight,9.0,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Lightweight,5.0,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,Middleweight,5.0,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,7.0,1913.0

In [181]:
#advanced funtionality
#shift() rank() consum() rolling()
latte= coffee[coffee['Coffee Type']=='Latte'].copy()
latte

          Day Coffee Type  Units Sold  price  revenue
1      Monday       Latte        10.0   5.99    59.90
3     Tuesday       Latte         NaN   5.99    59.90
5   Wednesday       Latte        25.0   5.99   149.75
7    Thursday       Latte        30.0   5.99   179.70
9      Friday       Latte        35.0   5.99   209.65
11   Saturday       Latte        35.0   5.99   209.65
13     Sunday       Latte        35.0   5.99   209.65

In [182]:
latte['3day'] = latte['Units Sold'].rolling(3).sum()
latte

          Day Coffee Type  Units Sold  price  revenue   3day
1      Monday       Latte        10.0   5.99    59.90    NaN
3     Tuesday       Latte         NaN   5.99    59.90    NaN
5   Wednesday       Latte        25.0   5.99   149.75    NaN
7    Thursday       Latte        30.0   5.99   179.70    NaN
9      Friday       Latte        35.0   5.99   209.65   90.0
11   Saturday       Latte        35.0   5.99   209.65  100.0
13     Sunday       Latte        35.0   5.99   209.65  105.0